spring.application.name=pp311
# MySQL properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/task_2_3_1?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate properties
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# For http_methods PUT, PATCH and DELETE fire
spring.mvc.hiddenmethod.filter.enabled=true